### ISSUE TITLE
not really an issue - just {questions about using the script} 

### ISSUE THREAD

**Issue by bododge** [chuanli11/CNNMRF#10]
I keep getting errors that say 'unknown required option type table' when trying to add in the **-num_iter** option. ( or any other options that include more than one value) 

It would be nice if there were example usage for each variable with this type of usage or syntax (below). Here's my example that does not work for me. How do you call the last three numbers?

`qlua cnnmrf.lua -content_name photo -style_name painting -backend cudnn -mode speed -num_iter {100, 100, 100}`

**Comment by dionysio** [comment]
This is indeed a bug. I will send PR soon.

**Comment by dionysio** [comment]
If the PR gets accepted, you can call it like this:
`qlua cnnmrf.lua -content_name photo -style_name painting -backend cudnn -mode speed -num_iter 100,100,100`
