### ISSUE TITLE
requiring cutorch even when using clnn backend

### ISSUE THREAD

**Issue by rayset** [chuanli11/CNNMRF#13]
`$ qlua run_trans.lua -style_image boccioni.jpg -content_image coppia.jpg -backend clnn`

gives me this error:

```
qlua: ./transfer_CNNMRF_wrapper.lua:352: module 'cutorch' not found:
    no field package.preload['cutorch']
    no file '/home/alex/.luarocks/share/lua/5.1/cutorch.lua'
    no file '/home/alex/.luarocks/share/lua/5.1/cutorch/init.lua'
    no file '/home/alex/torch/install/share/lua/5.1/cutorch.lua'
    no file '/home/alex/torch/install/share/lua/5.1/cutorch/init.lua'
    no file './cutorch.lua'
    no file '/home/alex/torch/install/share/luajit-2.1.0-beta1/cutorch.lua'
    no file '/usr/local/share/lua/5.1/cutorch.lua'
    no file '/usr/local/share/lua/5.1/cutorch/init.lua'
    no file '/home/alex/torch/install/lib/cutorch.so'
    no file '/home/alex/.luarocks/lib/lua/5.1/cutorch.so'
    no file '/home/alex/torch/install/lib/lua/5.1/cutorch.so'
    no file './cutorch.so'
    no file '/usr/local/lib/lua/5.1/cutorch.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: at 0x7f2b64c93f90
    [C]: in function 'require'
    ./transfer_CNNMRF_wrapper.lua:352: in function 'main'
    ./transfer_CNNMRF_wrapper.lua:579: in function 'run_test'
    /home/alex/CNNMRF/mylib/helper.lua:183: in function 'run_tests'
    run_trans.lua:72: in main chunk
```

any help? I saw that dionysio made the clnn back end a few weeks a go, maybe the pull request was missing some updates?

**Comment by rayset** [comment]
I removed the whole if at line 352 and made the code run as if I only could have clnn... now it works, so I guess there really is a problem over there? mine is just an hotfix for others that may get the same error before the author patches it.

**Comment by dionysio** [comment]
Hey, try running 
`qlua  cnnmrf.lua -style_image boccioni.jpg -content_image coppia.jpg -backend clnn`. 

The run_trans.lua and run_syn.lua scripts are an old interface. Sorry for this confusion, it might be worth rewriting Readme a little bit.

**Comment by rayset** [comment]
this works, thank you (parameters are now style_name and content_name).

the third resolution also takes 1 hour  and a half with my radeon R9 280x. is this reasonable or is there something wrong with my configuration?

If I may suggest a serious improvement, it would be giving the parameters used (or at least similar) to make the picture in the readme. the pictures I'm making atm seem just blurrier than the original...considering the time it needs to have a single run it would be nice having a basis to play on instead of learning everything the hard way.

Very nice work anyway, I can't wait to get some cool results.

**Comment by rayset** [comment]
ok,one last ''bug'', I finally got it working well.

your benchmarks confirm this behaviour. for clnn and only for clnn, the 'memory' setting is A LOT faster. in my case we are speaking of 2 minutes vs 90 for the same image.

my setup is a radeon r9 280x with 3gb of ram (as far I know,could be 2). If this is expected you may want to specify this huge difference for clnn in the helper.

**Comment by ddofer** [comment]
Which is the correct file to use, for the latest version on Git? (I get different errors for different scripts run. I'm Using ClNN + OpenCl backend.)
