### ISSUE TITLE
running on cpu mode

### ISSUE THREAD

**Issue by rayset** [chuanli11/CNNMRF#14]
I tough that giving -backend nn-cpu would use only my cpu, instead for a mistake of mine ( I edited the code) it run the opencl backend.
I see traces of a cpu mode in the code, but I can't quite figure it. is there any way? I've a huge server with no gpu and lots of ram I could use. neural style takes a few hours of work, so I guess this would be a few more,which is not a problem for me.

**Comment by mrmartin** [comment]
I've got mine working in cpu mode, it requires minor additions to the code. You essentially need to add a if params.gpu >= 0 statement around every :cuda()/:cl() block, and change net.forward() not to use :cl().

**Comment by rayset** [comment]
I tried yesterday the very same thing,but it end up saying it required (an wasn't finding) nn-cpu.lua.

could you upload your code on pastebin or something? thanks

**Comment by mrmartin** [comment]
I'm using nn instead of nn-cpu, and yes, I'll prepare a pull request

**Comment by rayset** [comment]
what do you mean ''using nn''? is nn-cpu an actual existing package? I didn't find it anywhere.

anyhow tank you very much,in advance, for the merge.

**Comment by mrmartin** [comment]
fixed with #15
