### ISSUE TITLE
How big images fit into a 4gb cuda gpu (like amazon's) ?

### ISSUE THREAD

**Issue by rayset** [chuanli11/CNNMRF#16]
for neural style it's around 800, but CNNMRF seems a bit more memory hungry.

I'm considering buying one just for this amazing software, but I don't know if it's worth the shot.

3 layers,all default settings,of course.

**Comment by schwittlick** [comment]
what kind of amazing software are you going to buy? get one of nvidia digits devboxes. and while you're at it, get me one too please c:

**Comment by rayset** [comment]
sadly I can't afford a titan just to deep styling, let alone 4 :P 

there are a lot of very cheap 4gb cards (even as low as 40$ for a cuda ddr3) and if a 800px immage fits I will get one for sure.

I'm considering a 8g 290, but it's not a cuda card, and opengl runs slower.

**Comment by mrmartin** [comment]
I can fit an 800x638 px image on my 3GB GeForce 780. It actually only takes 2.2GB of memory, so there's still room for a bigger one. It takes about 9 minutes. So a WVGA 5 minute film at 24 fps would take me 18 hours.
On the cpu, the same image takes about 18GB, taking half an hour. As you'll notice, the size grows very quickly. A 960 x 1280 image on the CPU already takes more than 30 GB of RAM, and takes hours. So a 720p film would take months on a CPU.
Buying more hardware will only get you so far, but I believe the code can be modified to handle far higher resolution on a GPU without more RAM. Have you thought about tiling your image?

**Comment by schwittlick** [comment]
Just fyi, I have failed to both, implement my own tiling and use an tiling approach somebody else developed. For my own implementation, I ended up with lots of artefacts at the edges of the tiles. Thus all tiles of the assembled image were very prominent. Here's another implementation, though I dont remember why I failed: https://github.com/mtyka/neural_artistic_style/blob/master/neural_artistic_style.py#L85 the -scale parameter is the one to look at. Let me know if you're successful

**Comment by rayset** [comment]
I guess cuda is so much better even in ram management then... I don't really care of computational time, so an old geforce with huge vram but slow gpu may be good.

@mrzl as soon as my windows azure finishes the current batch of images I'll try that implementation!

**Comment by ttoinou** [comment]
@mrzl : I succeeded in tiling on another code without artefacts, see https://github.com/yusuketomoto/chainer-fast-neuralstyle/issues/25 :) . But the image will never be perfect anyway.
