### ISSUE TITLE
Multiple Style Images

### ISSUE THREAD

**Issue by 3DTOPO** [chuanli11/CNNMRF#17]
The results I have seen so far are impressive. The one thing I am seem to be missing is support for multiple style images (I got hooked on the feature with Justin's Neural Style implementation).

If it might be straight forward to port over I will give it a shot. Perhaps it is much more difficult to implement with guided synthesis?

**Comment by bododge** [comment]
Bump ^ that would be sweet. I also wish I could directly control style scale. I seem to get some different results when using larger or smaller gpu_chunck1 sizes, but direct control over style scale would be neat.

**Comment by chuanli11** [comment]
Hi, 
I close this issue because researchers at Google has solved this problem in a very neat way. 
https://research.googleblog.com/2016/10/supercharging-style-transfer.html
