### ISSUE TITLE
run_trans.lua always uses the default images

### ISSUE THREAD

**Issue by MoritzLost** [chuanli11/CNNMRF#19]
I have no idea why, but instead of the content and style images I provide with the parameters `-style_name` and `-content_name`, the `run_trans.lua` script always uses the default ones (portrait1 and picasso). 

Here's my test command line input:

```
qlua run_trans.lua -style_name seated_nude -content_name IMG_6588 -max_size 500 -ini_method random -mode memory -backend cudnn
```

I checked that both images lie correctly in the respective directories, i.e.:

```
/data/style/seated_nude.jpg
/data/content/IMG_6588.jpg
```

However, when I run the command above, it just performs the transformation using portrait1.jpg and picasso.jpg (btw it does this indefinitely, i.e. once it's finished with resolution 3 it starts over at resolution 1, what's up with that?). I tried deleting those images, but then the script stops with an error complaining that they images are gone.

I have no idea what I'm doing wrong. Help would be greatly appreciated. Thanks!

**Comment by chuanli11** [comment]
Hi, @MoritzLost 

The run_trains script does not take command line input. You can hard code your test images in this file. See line 66.

Alternatively,  you can use 
qlua cnnmrf.lua -content_name IMG_6588 -style_name seated_nude -backend cudnn -mode speed -num_iter 100,100,100
