### ISSUE TITLE
Not an issue but seeking to replicate outputs from a service that appears similar to CNNMRF

### ISSUE THREAD

**Issue by ProGamerGov** [chuanli11/CNNMRF#26]
This album here: https://imgur.com/a/e24sj

I was using `-type transfer -mode memory` and content weight 2-10. I am very new to CNNMRF, and thus am unsure if any of the settings are capable of making the images compare to each other.

The "triangle style" is one of the most interesting styles I am trying to replicate: https://imgur.com/a/6ZWGJ Trying to get the CNNMRF output to look like the Dreamscopeapp output. 

Can @chuanli11 provide any assistance? Point me towards the right commands? Or point me towards a more suitable style transfer project for these goals?

**Comment by rayset** [comment]
according to dreamscope's owner it runs on neural style, and before seeing the leaf picture I would have been sure about it.

try to change mrf_weight a bit.

I also always wondered how results would be with 4 mrf layers instead of 3, if you have the vram to do it give it a shot.

**Comment by chuanli11** [comment]
Hi,  I guess neural style suits better for what dreamscope does. CNNMRF can be a bit too rigid -- unless you what have more style-faithful results.
