### ISSUE TITLE
Error RUnning CNNMRF

### ISSUE THREAD

**Issue by jbgrant01** [chuanli11/CNNMRF#27]
When I run qlua cnnmrf.lua I get through the network is built, syntheses started at resolution and implementing mrf layers. Then it throws the error:  /home/jim/CNNMRF/mylib/mrf.lua:167: attempt to call field 'SpatialConvolutionMM_updateOutput' (a nil value).

Not sure what I am doing wrong. I have torch and loadcaffe and cudnn running well using jcjohnson's neural-style. I just wanted to give CNNMRF a try as the results look more like what I am trying to achieve.

Thanks for any help.

**Comment by jbgrant01** [comment]
I see that issue #9 on the same issue is closed. However, I am still having the old issue.

**Comment by chuanli11** [comment]
Hi,
did you try updating both nn and cunn following the advice given here:
https://groups.google.com/d/msg/torch7/CnkUoI6Dh1E/wZrXJaXTAwAJ

Chuan (Chris) Li

Postdoc Researcher

Mainz University

**Comment by jbgrant01** [comment]
Thanks for the quick reply. Finally got nn and cunn (as well as cudnn) updated and got through the rmrf layers. Then it threw a new error:
Synthesis started at resolution 

---

Implementing mrf layers ...
qlua: ./transfer_CNNMRF_wrapper.lua:317: bad argument #3 to 'format' (number expected, got nil)
stack traceback:
    [C]: at 0x7f9fd62d39c0
    [C]: in function 'format'
    ./transfer_CNNMRF_wrapper.lua:317: in function 'maybe_print'
    ./transfer_CNNMRF_wrapper.lua:346: in function 'opfunc'
    /home/jim/CNNMRF/mylib/myoptimizer.lua:179: in function 'mylbfgs'
    ./transfer_CNNMRF_wrapper.lua:517: in function 'main'
    cnnmrf.lua:92: in main chunk
Not sure what is going on. Thanks for your help.

Jim

**Comment by jbgrant01** [comment]
I got it to work! Rather than trying to tun it with parameters specified I make another copy of run_trans.lua, made changes to the parameter list and got results similar to what you show in the readme.md. 

I think we can close this one.
