### ISSUE TITLE
different image with same parameters ..

### ISSUE THREAD

**Issue by lulu1315** [chuanli11/CNNMRF#29]
hello and thank you for the code.
I'm using -init_method 'image' , mrf_layers 12,21 , num_res 3 and pretty default parameters.this is with cudnn on Kubuntu 14.04.
when I rerender the same image with exactly the same parameters I get a different output result.I looked at the code looking for a random function somewhere but didn't find any.
do you have insights on why it behaves like this ?
neural transfert gives you the same result assuming that you have the same seed and same image as content.
just wondering if there could be a way to make it repeatable ...
thanks in advance
luc

**Comment by chuanli11** [comment]
Hi,
I guess you were using cudnn end, which kind of give slightly different result each time. It seems cuDNN's backward pass is by default non-deterministic.
http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html
