### ISSUE TITLE
About MRFMM:updateGradInput and MRFMM:updateOutput

### ISSUE THREAD

**Issue by Kenhouse** [chuanli11/CNNMRF#30]
Hi ,I have some questions about this two function. 
1.Why I can't see the MRF loss function calculation in MRFMM:updateOutput but in MRFMM:updateGradInput. Is there any special reasons?
2.In MRFMM:updateGradInput the gradTO is the MRF loss function result. Is it for simplification reason?

**Comment by chuanli11** [comment]
Hi, 
1. There is no special reason why it can't be in MRFMM:updateOutput. 
2. Right, gradTO is the MRF loss
